### ISSUE TITLE
Beta complete dialog fires for every sector everywhere

### ISSUE THREAD

**Issue by 000x91** [Sublemon-Team/Subvoyage#10]
You beat Encounter, the beta complete dialogue shows.

Later, you beat any sector on any planet, the same dialogue shows. Each sector complete. I don't think that is intended behavior

https://github.com/Sublemon-Team/Subvoyage/blob/e378a48d54e8921a7187c1f98d5b30e77300cbaf/src/subvoyage/SubvoyageMod.java#L98

**Comment by VuzZis** [comment]
oh... yeah will try to fix that

**Comment by VuzZis** [comment]
try to use the jar from latest github action
if it works write here,  i will make a new release with this bugfix

**Comment by 000x91** [comment]
the change works
