### ISSUE TITLE
tugRoller can't be researched

### ISSUE THREAD

**Issue by 000x91** [Sublemon-Team/Subvoyage#5]
TugRoller requires argonCondenser; argonCondenser requires tugSheet

https://github.com/Sublemon-Team/Subvoyage/blob/291a0f15cf7dd3b51c6baeedb9b422101d050c07/src/subvoyage/content/world/planets/atlacian/AtlacianTechTree.java#L124

**Comment by VuzZis** [comment]
oh, okay
fixed in dev version
