### ISSUE TITLE
Enable crudes on generative sectors

### ISSUE THREAD

**Issue by 000x91** [Sublemon-Team/Subvoyage#8]
Last version made the tectonic drill require the crudes terrain. You need crudes, thus the tectonic drill, for half the materials. The generator has the crudes part commented out

https://github.com/Sublemon-Team/Subvoyage/blob/536fcdc95397c42a68a5cb9cdd1170a203c57c4e/src/subvoyage/content/world/planets/atlacian/AtlacianPlanetGenerator.java#L303

**Comment by VuzZis** [comment]
it was commented because of wrong generation behaviour
in next update, this has been fixed
